error_log C:/Users/makar/nginx-1.30.5/logs/error.log;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include C:/Users/makar/nginx-1.30.5/conf/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout 65;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=1r/s;

    # 1. Группа бэкендов для балансировки
    upstream backend_nodes {
        server 127.0.0.1:5001;
        server 127.0.0.1:5002;
    }

    # Хост 1: Основной сервис
    server {
        listen 80 default_server;
        listen 443 ssl default_server;
        server_name _;

        ssl_certificate      C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/certs/selfsigned.crt;
        ssl_certificate_key  C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/certs/selfsigned.key;

        return 404;
    }

    # редирект на https
    server {
        listen       80;
        server_name  app.local;
        return 301 https://$host$request_uri;
    }

    # Основной HTTPS сервер (443)
    server {
        listen       443 ssl;
        server_name  app.local;

        ssl_certificate      C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/certs/selfsigned.crt;
        ssl_certificate_key  C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/certs/selfsigned.key;

        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;

        # Обработка пользовательской ошибки 404
        error_page 404 /404.html;
        location = /404.html {
            root C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/html;
            internal;
        }

        # Раздача статического фронтенда (из Лабы 0)
        location / {
            root C:/Users/makar/DevOps-from-CloudyVozduhan-team/laba_0_ben/frontend;
            index index.html;
        }

        # Alias: альтернативный путь к документации
        location /docs/ {
            alias C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/html/docs/;
            index index.html;
        }

        location /admin/ {
            auth_basic "Restricted Admin Area";
            auth_basic_user_file C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/.htpasswd;

            alias C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/html/admin/;
            index index.html;
        }

        # Проксирование запросов к бэкендам с балансировкой
        location /api/ {
            limit_req zone=api_limit burst=3 nodelay;
            limit_req_status 429;

            proxy_pass http://backend_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Хост 2: Виртуальный хост (second.local)
    server {
        listen       80;
        server_name  second.local;

        location / {
            root C:/Users/makar/DevOps-from-CloudyVozduhan-team/lab1/html/second;
            index index.html;
        }
    }
}